### ISSUE TITLE
Integrate smolagents open_deep_research as a GitHub Action Triggered by Issue Comments

### ISSUE THREAD

**Issue by nimishchaudhari** [nimishchaudhari/openhands_working_dir#13]
We aim to integrate the `smolagents` library's `open_deep_research` example (available at [https://github.com/huggingface/smolagents/tree/main/examples/open_deep_research](https://github.com/huggingface/smolagents/tree/main/examples/open_deep_research)) as a GitHub Action. The action should:

- Be triggered when a user comments `@smol_researcher` in an issue.
- Use the `gpt-4o-mini` model.
- Process the issue's context (title, body, and the triggering comment).
- Run the research script with this context.
- Post the script's output as a comment in the same issue thread, under the comment where the agent was invoked.

This will enable users to request research assistance interactively within GitHub issues.

### Requirements

- **Trigger:** Activate the GitHub Action when an issue comment contains `@smol_researcher`.
- **Context Retrieval:** Extract the issue's title, body, and the triggering comment.
- **Input Preparation:** Format the context into an input suitable for the research script.
- **Environment Setup:** Configure a Python environment with `smolagents` and dependencies.
- **Model Configuration:** Set the script to use the `gpt-4o-mini` model, authenticating with an OpenAI API key stored securely.
- **Execution:** Run the script with the prepared input and capture its output.
- **Output Posting:** Post the script’s output as a comment in the issue thread.
- **Error Handling:** Provide feedback if the script fails or produces no output.

#### Step 1: Create the GitHub Action Workflow

Define a workflow file (e.g., `.github/workflows/smol-researcher.yml`) to handle the trigger and orchestrate the process.

**Workflow File Example:**

```yaml
name: Smol Researcher

on:
  issue_comment:
    types: [created]

jobs:
  research:
    if: contains(github.event.comment.body, '@smol_researcher')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install smolagents
          # Add other dependencies if required (e.g., from a requirements.txt)

      - name: Prepare input
        run: |
          comment_body=$(echo "${{ github.event.comment.body }}" | sed 's/@smol_researcher//')
          echo "User request: $comment_body" > input.txt
          echo "Issue context:" >> input.txt
          echo "Title: ${{ github.event.issue.title }}" >> input.txt
          echo "Body: ${{ github.event.issue.body }}" >> input.txt

      - name: Run research script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/research_agent.py --model gpt-4o-mini --input input.txt --output output.txt

      - name: Post result as comment
        run: |
          if [ -s output.txt ]; then
            output=$(cat output.txt)
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"body\": \"Smol Researcher Result:\n\n$output\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
          else
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"body\": \"Unable to process the request at this time.\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
          fi
```

- **Trigger:** The `issue_comment` event with `types: [created]` listens for new comments. The `if` condition filters for `@smol_researcher`.
- **Steps:**
  - Check out the repository.
  - Set up Python.
  - Install `smolagents` (and other dependencies).
  - Prepare an input file with the issue context.
  - Run a custom script (to be created).
  - Post the output as a comment using the GitHub API, with error handling.

#### Step 2: Create a Custom Research Script

The `open_deep_research` example (`run.py`) is designed for the GAIA benchmark, processing multiple examples. We’ll create a new script (e.g., `scripts/research_agent.py`) tailored for single-input processing.

**Script Example (`scripts/research_agent.py`):**

```python
import os
from smolagents import CodeAgent, LiteLLMModel
from scripts.text_inspector_tool import TextInspectorTool
from scripts.text_web_browser import SimpleTextBrowser

def main(input_file, output_file, model_id):
    # Read input
    with open(input_file, 'r') as f:
        input_text = f.read()

    # Configure model
    model = LiteLLMModel(model_id=model_id, api_key=os.environ['OPENAI_API_KEY'])

    # Set up tools (based on open_deep_research example)
    text_inspector = TextInspectorTool(model)
    web_browser = SimpleTextBrowser()
    tools = [text_inspector, web_browser]

    # Define system prompt
    system_prompt = (
        "You are a helpful research assistant. Analyze the user's request and the issue context "
        "to provide relevant information or solutions. Use your tools as needed."
    )

    # Create and run agent
    agent = CodeAgent(model=model, tools=tools, system_prompt=system_prompt)
    result = agent.run(input_text)

    # Write output
    with open(output_file, 'w') as f:
        f.write(result)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Run research agent with smolagents")
    parser.add_argument('--model', required=True, help="Model ID (e.g., gpt-4o-mini)")
    parser.add_argument('--input', required=True, help="Path to input file")
    parser.add_argument('--output', required=True, help="Path to output file")
    args = parser.parse_args()
    main(args.input, args.output, args.model)
```

- **Imports:** Use `CodeAgent` and `LiteLLMModel` from `smolagents`, plus tools from the example.
- **Model:** Set to `gpt-4o-mini` via command-line argument, using the API key from the environment.
- **Tools:** Include `TextInspectorTool` and `SimpleTextBrowser` (adjust based on the actual example’s tools).
- **Prompt:** Guide the agent to process the request and context.
- **Execution:** Read input, run the agent, and write output.

#### Step 3: Securely Store the API Key

- Go to your GitHub repository’s **Settings > Secrets and variables > Actions**.
- Add a new secret named `OPENAI_API_KEY` with your OpenAI API key.
- The workflow accesses it via `${{ secrets.OPENAI_API_KEY }}`.

#### Step 4: Test the Integration

1. Create a test issue in your repository.
2. Comment `@smol_researcher` (optionally with a specific request, e.g., `@smol_researcher find info on X`).
3. Verify that:
   - The action triggers (check the Actions tab).
   - An input file is created with the issue context.
   - The script runs and produces an output.
   - A comment appears with the result or an error message.

### Additional Considerations

- **Security:** The script uses external tools (e.g., web browser). Consider sandboxing with Docker or E2B (supported by `smolagents`) if security is a concern, though this adds complexity.
- **Timeouts:** GitHub Actions have a 6-hour limit per job, but optimize the script to avoid delays (e.g., limit web searches).
- **Rate Limits/Costs:** Monitor OpenAI API usage to manage costs, especially if triggered frequently.
- **Output Formatting:** Ensure the output is readable (e.g., use Markdown). If too long, truncate or split it (GitHub comment limit is ~65,535 characters).
- **Error Handling:** The workflow already handles empty outputs; enhance the script with try-except blocks if needed.

### Next Steps

1. **Implement the Script:** Create `scripts/research_agent.py` in your repository, adapting tools and configuration from `open_deep_research/run.py`.
2. **Set Up Workflow:** Add the `.github/workflows/smol-researcher.yml` file.
3. **Configure Secrets:** Add the `OPENAI_API_KEY` to GitHub Secrets.
4. **Test and Refine:** Run tests, adjust the prompt or tools as needed, and ensure robust error handling.

### Conclusion

This plan integrates the `smolagents` `open_deep_research` functionality into a GitHub Action, triggered by `@smol_researcher` comments. It leverages the issue context, processes it with the `gpt-4o-mini` model, and delivers results back to the issue thread, enhancing collaboration and automation in your repository.
