### ISSUE TITLE
Modifications in deep research

### ISSUE THREAD

**Issue by nimishchaudhari** [nimishchaudhari/openhands_working_dir#15]
To modify your existing script and GitHub Actions workflow to use the `LLM_API_KEY` environment secret for the API key and the `LLM_MODEL` environment variable for the model ID in your Python file, I'll outline the necessary changes. These modifications assume you have a GitHub Action setup that runs a Python script, and you want to shift from passing the API key and model as command-line arguments to using environment variables for better security and flexibility. Below, I’ll provide a clear, step-by-step guide to update both the workflow and the script.

---

### Modifications to the GitHub Actions Workflow

The workflow file (e.g., `.github/workflows/smol-researcher.yml`) needs to set the `LLM_API_KEY` and `LLM_MODEL` environment variables so they are available to the Python script. Since `LLM_API_KEY` is sensitive, it should be stored as a GitHub Secret, while `LLM_MODEL` can be defined directly in the workflow (e.g., as `gpt-4o-mini`). These variables should be set at the job level to ensure all steps can access them.

#### Updated Workflow File Example

```yaml
name: Smol Researcher

on:
  issue_comment:
    types: [created]

jobs:
  research:
    if: contains(github.event.comment.body, '@smol_researcher')
    runs-on: ubuntu-latest
    env:
      LLM_MODEL: gpt-4o-mini  # Set the model ID here (customize as needed)
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}  # Use the secret for the API key
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install smolagents
          # Add other dependencies if needed (e.g., pip install -r requirements.txt)

      - name: Prepare input
        run: |
          comment_body=$(echo "${{ github.event.comment.body }}" | sed 's/@smol_researcher//')
          echo "User request: $comment_body" > input.txt
          echo "Issue context:" >> input.txt
          echo "Title: ${{ github.event.issue.title }}" >> input.txt
          echo "Body: ${{ github.event.issue.body }}" >> input.txt

      - name: Run research script
        run: |
          python scripts/research_agent.py --input input.txt --output output.txt

      - name: Post result as comment
        run: |
          if [ -s output.txt ]; then
            output=$(cat output.txt)
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"body\": \"Smol Researcher Result:\n\n$output\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
          else
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"body\": \"Unable to process the request at this time.\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
          fi
```

#### Key Changes in the Workflow

1. **Environment Variables at Job Level:**
   - Added `env` section under `jobs.research`:
     - `LLM_MODEL: gpt-4o-mini`: Specifies the model ID (e.g., `gpt-4o-mini`). You can change this value as needed.
     - `LLM_API_KEY: ${{ secrets.LLM_API_KEY }}`: Pulls the API key from a GitHub Secret named `LLM_API_KEY`.

2. **Script Invocation:**
   - Removed `--model` and `--api_key` arguments from the `python scripts/research_agent.py` command, as these will now be accessed via environment variables within the script.

3. **Secret Configuration:**
   - Ensure you’ve added a secret named `LLM_API_KEY` in your GitHub repository:
     - Go to **Settings > Secrets and variables > Actions**.
     - Add a new secret named `LLM_API_KEY` with your API key value (e.g., your OpenAI API key).

---

### Modifications to the Python Script

The Python script (e.g., `scripts/research_agent.py`) needs to be updated to read `LLM_API_KEY` and `LLM_MODEL` from the environment instead of expecting them as command-line arguments. We’ll remove the corresponding `argparse` arguments and use `os.environ` to access these variables, adding basic error handling for robustness.

#### Updated Script Example

```python
import os
import sys
from smolagents import CodeAgent, LiteLLMModel
from scripts.text_inspector_tool import TextInspectorTool  # Adjust import paths as needed
from scripts.text_web_browser import SimpleTextBrowser  # Adjust import paths as needed

def main(input_file, output_file):
    # Retrieve environment variables with error handling
    try:
        model_id = os.environ['LLM_MODEL']
        api_key = os.environ['LLM_API_KEY']
    except KeyError as e:
        print(f"Error: Environment variable {e} is not set.")
        sys.exit(1)

    # Read input from file
    with open(input_file, 'r') as f:
        input_text = f.read()

    # Configure the model with environment variables
    model = LiteLLMModel(model_id=model_id, api_key=api_key)

    # Set up tools (example from open_deep_research)
    text_inspector = TextInspectorTool(model)
    web_browser = SimpleTextBrowser()
    tools = [text_inspector, web_browser]

    # Define system prompt
    system_prompt = (
        "You are a helpful research assistant. Analyze the user's request and the issue context "
        "to provide relevant information or solutions. Use your tools as needed."
    )

    # Create and run the agent
    agent = CodeAgent(model=model, tools=tools, system_prompt=system_prompt)
    result = agent.run(input_text)

    # Write the result to the output file
    with open(output_file, 'w') as f:
        f.write(result)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Run research agent with smolagents")
    parser.add_argument('--input', required=True, help="Path to input file")
    parser.add_argument('--output', required=True, help="Path to output file")
    args = parser.parse_args()
    main(args.input, args.output)
```

#### Key Changes in the Script

1. **Remove Command-Line Arguments:**
   - Removed `--model` and `--api_key` from the `argparse` setup since they are no longer passed via the command line.
   - Kept `--input` and `--output` as they are still needed for file paths.

2. **Access Environment Variables:**
   - Added:
     ```python
     model_id = os.environ['LLM_MODEL']
     api_key = os.environ['LLM_API_KEY']
     ```
   - These lines fetch the model ID and API key from the environment variables set by the workflow.

3. **Error Handling:**
   - Wrapped the environment variable access in a `try-except` block:
     ```python
     try:
         model_id = os.environ['LLM_MODEL']
         api_key = os.environ['LLM_API_KEY']
     except KeyError as e:
         print(f"Error: Environment variable {e} is not set.")
         sys.exit(1)
     ```
   - If either `LLM_MODEL` or `LLM_API_KEY` is missing, the script will exit with a clear error message, which will appear in the GitHub Actions logs.

4. **Update `main` Function:**
   - Adjusted the `main` function signature to `main(input_file, output_file)` since `model_id` and `api_key` are now sourced internally.
   - The `LiteLLMModel` initialization uses the retrieved `model_id` and `api_key`.

---

#### 1. Verify GitHub Secrets
- Ensure the `LLM_API_KEY` secret is correctly set in your repository:
  - Navigate to **Settings > Secrets and variables > Actions > Secrets**.
  - Add or verify a secret named `LLM_API_KEY` with your API key.

#### 2. Test the Changes
- **Create a Test Issue:**
  - Open an issue in your repository and comment `@smol_researcher` (e.g., `@smol_researcher tell me about Python`).
- **Check the Action:**
  - Go to the **Actions** tab in your repository.
  - Verify that the workflow runs, the script executes, and a result is posted as a comment.
- **Debugging:**
  - If the job fails, check the logs for errors (e.g., missing `LLM_API_KEY` or dependency issues).

#### 3. Adjust Dependencies
- The script assumes `smolagents` is installed and that tools like `TextInspectorTool` and `SimpleTextBrowser` are available. Update the `Install dependencies` step in the workflow if additional packages or files are required:
  ```bash
  pip install -r requirements.txt
  ```
  - Add a `requirements.txt` file if needed.

---

### Summary of Changes

- **Workflow:**
  - Added `env` at the job level with `LLM_MODEL: gpt-4o-mini` and `LLM_API_KEY: ${{ secrets.LLM_API_KEY }}`.
  - Removed `--model` and `--api_key` from the script invocation.
- **Script:**
  - Removed `--model` and `--api_key` from `argparse`.
  - Added logic to read `LLM_MODEL` and `LLM_API_KEY` from `os.environ` with error handling.
  - Adjusted the `main` function to use these variables directly.

These modifications ensure your script uses the `LLM_API_KEY` environment secret for the API key and the `LLM_MODEL` environment variable for the model ID, aligning with your request for a more secure and maintainable setup. Let me know if you need further clarification or assistance!
