### ISSUE TITLE
Set up this as a kubernetes cluster

### ISSUE THREAD

**Issue by nimishchaudhari** [nimishchaudhari/openhands_working_dir#24]
In 'k8s' folder set the foollowing project

Below is a complete Kubernetes setup that converts your remaining docker-compose services into Kubernetes Deployments, Services, and PersistentVolumeClaims. I’ve also added a README file with instructions and a Windows batch script (run-k8s.bat) to deploy everything with kubectl. This setup is a simplified conversion and may need tweaks (especially around hostPath volumes and security settings) to suit your environment.
---

### **Kubernetes YAML (all-resources.yaml)**

```yaml
# k8s/all-resources.yaml

#############################################
# PersistentVolumeClaims for persistent data
#############################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
#############################################
# 11000_personal-website Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website
  labels:
    app: personal-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-website
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
      - name: personal-website
        image: my-personal-website:latest
        ports:
        - containerPort: 11000
---
apiVersion: v1
kind: Service
metadata:
  name: personal-website
spec:
  type: NodePort
  selector:
    app: personal-website
  ports:
  - protocol: TCP
    port: 11000
    targetPort: 11000
    nodePort: 31100
---
#############################################
# 11002_anythingllm Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anythingllm
  labels:
    app: anythingllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anythingllm
  template:
    metadata:
      labels:
        app: anythingllm
    spec:
      containers:
      - name: anythingllm
        image: mintplexlabs/anythingllm:latest
        ports:
        - containerPort: 3001
        env:
          - name: STORAGE_DIR
            value: "/app/server/storage"
          - name: JWT_SECRET
            value: "XryIRjv0ioDzfXryIRjv0ioDzfXryIRjv0ioDzf"
          - name: VECTOR_DB
            value: "lancedb"
          - name: WHISPER_PROVIDER
            value: "local"
          - name: TTS_PROVIDER
            value: "native"
          - name: PASSWORDMINCHAR
            value: "8"
        volumeMounts:
          - name: anythingllm-storage
            mountPath: /app/server/storage
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
      volumes:
      - name: anythingllm-storage
        persistentVolumeClaim:
          claimName: anythingllm-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: anythingllm
spec:
  type: NodePort
  selector:
    app: anythingllm
  ports:
  - protocol: TCP
    port: 11002
    targetPort: 3001
    nodePort: 31102
---
#############################################
# 11003_code-server Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  labels:
    app: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: lscr.io/linuxserver/code-server:latest
        ports:
        - containerPort: 8443
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Etc/UTC"
          - name: PASSWORD
            value: "123123dr"
          - name: SUDO_PASSWORD
            value: "123123dr"
          - name: PROXY_DOMAIN
            value: "code.jetpack-ai.net"
          - name: DEFAULT_WORKSPACE
            value: "/config/workspace"
        volumeMounts:
          - name: code-server-config
            mountPath: /config
      volumes:
      - name: code-server-config
        persistentVolumeClaim:
          claimName: code-server-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
spec:
  type: NodePort
  selector:
    app: code-server
  ports:
  - protocol: TCP
    port: 11003
    targetPort: 8443
    nodePort: 31103
---
#############################################
# 11004_n8n Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n
        ports:
        - containerPort: 5678
        env:
          - name: host
            value: "n8n.jetpack-ai.net"
        volumeMounts:
          - name: n8n-data
            mountPath: /home/node/.n8n
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  type: NodePort
  selector:
    app: n8n
  ports:
  - protocol: TCP
    port: 11004
    targetPort: 5678
    nodePort: 31104
---
#############################################
# 11006_open-webui Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: open-webui-data
            mountPath: /app/backend/data
      volumes:
      - name: open-webui-data
        persistentVolumeClaim:
          claimName: open-webui-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
  - protocol: TCP
    port: 11006
    targetPort: 8080
    nodePort: 31106
---
#############################################
# 11010_openhands Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhands
  labels:
    app: openhands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhands
  template:
    metadata:
      labels:
        app: openhands
    spec:
      containers:
      - name: openhands
        image: docker.all-hands.dev/all-hands-ai/openhands:0.26
        ports:
        - containerPort: 3000
        env:
          - name: SANDBOX_RUNTIME_CONTAINER_IMAGE
            value: "docker.all-hands.dev/all-hands-ai/runtime:0.26-nikolaik"
          - name: LOG_ALL_EVENTS
            value: "true"
          - name: WORKSPACE_MOUNT_PATH
            value: "/opt/workspace_base"
          - name: SANDBOX_RUNTIME
            value: "daytona"
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: openhands-state
            mountPath: /.openhands-state
          - name: workspace-base
            mountPath: /opt/workspace_base
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: openhands-state
        hostPath:
          path: "C:/Users/Nimish/.openhands-state"
      - name: workspace-base
        hostPath:
          path: "./workspace"  # Adjust as needed
---
apiVersion: v1
kind: Service
metadata:
  name: openhands
spec:
  type: NodePort
  selector:
    app: openhands
  ports:
  - protocol: TCP
    port: 11010
    targetPort: 3000
    nodePort: 31110
---
#############################################
# 11103_watchtower Deployment
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchtower
  labels:
    app: watchtower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchtower
  template:
    metadata:
      labels:
        app: watchtower
    spec:
      containers:
      - name: watchtower
        image: containrrr/watchtower
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
---
#############################################
# 11012_litellm Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  labels:
    app: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:litellm_stable_release_branch-v1.61.13-stable
        ports:
        - containerPort: 4000
        env:
          - name: STORE_MODEL_IN_DB
            value: "True"
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres@42110_khoj-database:5432/postgres"
          - name: LITELLM_MASTER_KEY
            value: "sk-1234"
          - name: LITELLM_SALT_KEY
            value: "sk-XXXXXXXX"
---
apiVersion: v1
kind: Service
metadata:
  name: litellm
spec:
  type: NodePort
  selector:
    app: litellm
  ports:
  - protocol: TCP
    port: 11012
    targetPort: 4000
    nodePort: 31112
```

---

### **README.md**

```markdown
# Kubernetes Deployment for Your Services

This repository contains Kubernetes manifests for deploying the following services:
- **Personal Website (11000_personal-website)**
- **AnythingLLM (11002_anythingllm)**
- **Code Server (11003_code-server)**
- **n8n (11004_n8n)**
- **Open-WebUI (11006_open-webui)**
- **OpenHands (11010_openhands)**
- **Watchtower (11103_watchtower)**
- **LiteLLM (11012_litellm)**

## Files

- **k8s/all-resources.yaml**: Contains all Kubernetes resources (Deployments, Services, PVCs).
- **run-k8s.bat**: A Windows batch script to deploy all resources.
- **README.md**: This file.

## Prerequisites

- [kubectl](https://kubernetes.io/docs/tasks/tools/) installed and configured to access your cluster.
- A running Kubernetes cluster.
- (Optional) Adjust hostPath volume paths in the YAML as needed for your environment.

## How to Deploy

1. Open a terminal (or Command Prompt if on Windows).

2. Apply the Kubernetes resources:
   ```bash
   kubectl apply -f k8s/all-resources.yaml
   ```

3. To verify the deployments:
   ```bash
   kubectl get deployments
   kubectl get services
   ```

## How to Use the Batch Script (Windows)

Simply double-click the **run-k8s.bat** file or run it from the Command Prompt:
   ```cmd
   run-k8s.bat
   ```

This script applies the manifests automatically.

## Notes

- **Persistent Storage**: The YAML defines PersistentVolumeClaims. You may need to configure your storage class or adjust sizes based on your requirements.
- **HostPath Volumes**: Some services (like OpenHands and Watchtower) use hostPath volumes. Make sure the paths exist on your host system and have the proper permissions.
- **Environment Variables**: Verify that the environment variables match your production settings.
- **Security Settings**: Some containers (e.g., AnythingLLM) require additional capabilities (like SYS_ADMIN). Ensure your cluster’s security policies allow these settings.

For more details on Kubernetes Deployments and Services, please refer to the [[Kubernetes Deployments documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) citek8s-deployment-doc and the [[Kubernetes Services documentation](https://kubernetes.io/docs/concepts/services-networking/service/)](https://kubernetes.io/docs/concepts/services-networking/service/) citek8s-service-doc.
```

---

### **Batch Script (run-k8s.bat)**

```batch
@echo off
echo Deploying Kubernetes resources...
kubectl apply -f k8s/all-resources.yaml
if %ERRORLEVEL% neq 0 (
    echo Failed to deploy Kubernetes resources.
    pause
    exit /b %ERRORLEVEL%
)
echo Kubernetes resources deployed successfully!
pause
```

---

### **Citations**

- Kubernetes Deployments documentation: citek8s-deployment-doc  
- Kubernetes Services documentation: citek8s-service-doc  
- Kubernetes Persistent Volumes documentation: citek8s-pv-doc

---

This setup should give you a solid starting point for running your services on Kubernetes. Let me know if you need further adjustments or have any questions!t up the project as described below. 

Below is a complete Kubernetes setup that converts your remaining docker-compose services into Kubernetes Deployments, Services, and PersistentVolumeClaims. I’ve also added a README file with instructions and a Windows batch script (run-k8s.bat) to deploy everything with kubectl. This setup is a simplified conversion and may need tweaks (especially around hostPath volumes and security settings) to suit your environment.

Feel free to review the YAML and let me know if you need any adjustments!

---

### **Kubernetes YAML (all-resources.yaml)**

```yaml
# k8s/all-resources.yaml

#############################################
# PersistentVolumeClaims for persistent data
#############################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
#############################################
# 11000_personal-website Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website
  labels:
    app: personal-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-website
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
      - name: personal-website
        image: my-personal-website:latest
        ports:
        - containerPort: 11000
---
apiVersion: v1
kind: Service
metadata:
  name: personal-website
spec:
  type: NodePort
  selector:
    app: personal-website
  ports:
  - protocol: TCP
    port: 11000
    targetPort: 11000
    nodePort: 31100
---
#############################################
# 11002_anythingllm Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anythingllm
  labels:
    app: anythingllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anythingllm
  template:
    metadata:
      labels:
        app: anythingllm
    spec:
      containers:
      - name: anythingllm
        image: mintplexlabs/anythingllm:latest
        ports:
        - containerPort: 3001
        env:
          - name: STORAGE_DIR
            value: "/app/server/storage"
          - name: JWT_SECRET
            value: "XryIRjv0ioDzfXryIRjv0ioDzfXryIRjv0ioDzf"
          - name: VECTOR_DB
            value: "lancedb"
          - name: WHISPER_PROVIDER
            value: "local"
          - name: TTS_PROVIDER
            value: "native"
          - name: PASSWORDMINCHAR
            value: "8"
        volumeMounts:
          - name: anythingllm-storage
            mountPath: /app/server/storage
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
      volumes:
      - name: anythingllm-storage
        persistentVolumeClaim:
          claimName: anythingllm-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: anythingllm
spec:
  type: NodePort
  selector:
    app: anythingllm
  ports:
  - protocol: TCP
    port: 11002
    targetPort: 3001
    nodePort: 31102
---
#############################################
# 11003_code-server Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  labels:
    app: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: lscr.io/linuxserver/code-server:latest
        ports:
        - containerPort: 8443
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Etc/UTC"
          - name: PASSWORD
            value: "123123dr"
          - name: SUDO_PASSWORD
            value: "123123dr"
          - name: PROXY_DOMAIN
            value: "code.jetpack-ai.net"
          - name: DEFAULT_WORKSPACE
            value: "/config/workspace"
        volumeMounts:
          - name: code-server-config
            mountPath: /config
      volumes:
      - name: code-server-config
        persistentVolumeClaim:
          claimName: code-server-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
spec:
  type: NodePort
  selector:
    app: code-server
  ports:
  - protocol: TCP
    port: 11003
    targetPort: 8443
    nodePort: 31103
---
#############################################
# 11004_n8n Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n
        ports:
        - containerPort: 5678
        env:
          - name: host
            value: "n8n.jetpack-ai.net"
        volumeMounts:
          - name: n8n-data
            mountPath: /home/node/.n8n
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  type: NodePort
  selector:
    app: n8n
  ports:
  - protocol: TCP
    port: 11004
    targetPort: 5678
    nodePort: 31104
---
#############################################
# 11006_open-webui Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: open-webui-data
            mountPath: /app/backend/data
      volumes:
      - name: open-webui-data
        persistentVolumeClaim:
          claimName: open-webui-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
  - protocol: TCP
    port: 11006
    targetPort: 8080
    nodePort: 31106
---
#############################################
# 11010_openhands Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhands
  labels:
    app: openhands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhands
  template:
    metadata:
      labels:
        app: openhands
    spec:
      containers:
      - name: openhands
        image: docker.all-hands.dev/all-hands-ai/openhands:0.26
        ports:
        - containerPort: 3000
        env:
          - name: SANDBOX_RUNTIME_CONTAINER_IMAGE
            value: "docker.all-hands.dev/all-hands-ai/runtime:0.26-nikolaik"
          - name: LOG_ALL_EVENTS
            value: "true"
          - name: WORKSPACE_MOUNT_PATH
            value: "/opt/workspace_base"
          - name: SANDBOX_RUNTIME
            value: "daytona"
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: openhands-state
            mountPath: /.openhands-state
          - name: workspace-base
            mountPath: /opt/workspace_base
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: openhands-state
        hostPath:
          path: "C:/Users/Nimish/.openhands-state"
      - name: workspace-base
        hostPath:
          path: "./workspace"  # Adjust as needed
---
apiVersion: v1
kind: Service
metadata:
  name: openhands
spec:
  type: NodePort
  selector:
    app: openhands
  ports:
  - protocol: TCP
    port: 11010
    targetPort: 3000
    nodePort: 31110
---
#############################################
# 11103_watchtower Deployment
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchtower
  labels:
    app: watchtower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchtower
  template:
    metadata:
      labels:
        app: watchtower
    spec:
      containers:
      - name: watchtower
        image: containrrr/watchtower
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
---
#############################################
# 11012_litellm Deployment & Service
#############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  labels:
    app: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:litellm_stable_release_branch-v1.61.13-stable
        ports:
        - containerPort: 4000
        env:
          - name: STORE_MODEL_IN_DB
            value: "True"
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres@42110_khoj-database:5432/postgres"
          - name: LITELLM_MASTER_KEY
            value: "sk-1234"
          - name: LITELLM_SALT_KEY
            value: "sk-XXXXXXXX"
---
apiVersion: v1
kind: Service
metadata:
  name: litellm
spec:
  type: NodePort
  selector:
    app: litellm
  ports:
  - protocol: TCP
    port: 11012
    targetPort: 4000
    nodePort: 31112
```

---

### **README.md**

```markdown
# Kubernetes Deployment for Your Services

This repository contains Kubernetes manifests for deploying the following services:
- **Personal Website (11000_personal-website)**
- **AnythingLLM (11002_anythingllm)**
- **Code Server (11003_code-server)**
- **n8n (11004_n8n)**
- **Open-WebUI (11006_open-webui)**
- **OpenHands (11010_openhands)**
- **Watchtower (11103_watchtower)**
- **LiteLLM (11012_litellm)**

## Files

- **k8s/all-resources.yaml**: Contains all Kubernetes resources (Deployments, Services, PVCs).
- **run-k8s.bat**: A Windows batch script to deploy all resources.
- **README.md**: This file.

## Prerequisites

- [kubectl](https://kubernetes.io/docs/tasks/tools/) installed and configured to access your cluster.
- A running Kubernetes cluster.
- (Optional) Adjust hostPath volume paths in the YAML as needed for your environment.

## How to Deploy

1. Open a terminal (or Command Prompt if on Windows).

2. Apply the Kubernetes resources:
   ```bash
   kubectl apply -f k8s/all-resources.yaml
   ```

3. To verify the deployments:
   ```bash
   kubectl get deployments
   kubectl get services
   ```

## How to Use the Batch Script (Windows)

Simply double-click the **run-k8s.bat** file or run it from the Command Prompt:
   ```cmd
   run-k8s.bat
   ```

This script applies the manifests automatically.

## Notes

- **Persistent Storage**: The YAML defines PersistentVolumeClaims. You may need to configure your storage class or adjust sizes based on your requirements.
- **HostPath Volumes**: Some services (like OpenHands and Watchtower) use hostPath volumes. Make sure the paths exist on your host system and have the proper permissions.
- **Environment Variables**: Verify that the environment variables match your production settings.
- **Security Settings**: Some containers (e.g., AnythingLLM) require additional capabilities (like SYS_ADMIN). Ensure your cluster’s security policies allow these settings.

For more details on Kubernetes Deployments and Services, please refer to the [[Kubernetes Deployments documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) citek8s-deployment-doc and the [[Kubernetes Services documentation](https://kubernetes.io/docs/concepts/services-networking/service/)](https://kubernetes.io/docs/concepts/services-networking/service/) citek8s-service-doc.
```

---

### **Batch Script (run-k8s.bat)**

```batch
@echo off
echo Deploying Kubernetes resources...
kubectl apply -f k8s/all-resources.yaml
if %ERRORLEVEL% neq 0 (
    echo Failed to deploy Kubernetes resources.
    pause
    exit /b %ERRORLEVEL%
)
echo Kubernetes resources deployed successfully!
pause
```

---

### **Citations**

- Kubernetes Deployments documentation: citek8s-deployment-doc  
- Kubernetes Services documentation: citek8s-service-doc  
- Kubernetes Persistent Volumes documentation: citek8s-pv-doc

---
